apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: "helloworld:gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
          imagePullPolicy: IfNotPresent